VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.network :forwarded_port, guest: 8000, host: 8000
  config.vm.network :private_network, ip: "192.168.100.100"
  config.vm.synced_folder "../", "/vagrant", type: "nfs"
  config.ssh.forward_agent = true

  config.vm.provider :virtualbox do |vb|
    vb.name = "ubuntu"
    vb.customize [
      "modifyvm", :id,
      "--name", "ubuntu",
      "--memory", 1024,
      "--natdnshostresolver1", "on",
      "--cpus", 1,
    ]
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
    ansible.extra_vars = {
      private_interface: "192.168.100.100",
      hostname: "ubuntu"
    }
  end

end
