sylius_resource:
    resources:
        app.post:
            driver: doctrine/orm
            classes:
                model: AppBundle\Entity\Post
        app.comment:
            driver: doctrine/orm
            classes:
                model: AppBundle\Entity\Comment
        app.tag:
            driver: doctrine/orm
            classes:
                model: AppBundle\Entity\Tag
