app_post:
    resource: app.post
    type:     sylius.api

app_comment:
    resource: app.comment
    type:     sylius.api

app_tag:
    resource: app.tag
    type:     sylius.api

# additional routes

app_api_post_comments:
    path: /posts/{id}/comments/
    defaults:
        _controller: app.controller.comment:indexAction
        _sylius:
            filterable: true
            criteria:
                post: $id
